import { Quicksand } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";


const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
   title: "Food-Next-App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={quicksand.className}>
            <Header />
            {children}
         </body>
      </html>
   );
}
